### ISSUE TITLE
unit testing with intern

### ISSUE THREAD

**Issue by rhpijnacker** [OpenNTF/dojo-webpack-plugin#123]
Hi Chuck,

Do you have any experience how to set up intern unit tests in combination with the dojo-webpack-plugin?

Kind regards, Ronald

**Comment by chuckdumont** [comment]
No, I don't.  But if you figure it out then I'd be happy to add your steps to the README.

**Comment by rhpijnacker** [comment]
I have the first tests running with intern 4, taking some inspiration from https://github.com/theintern/intern-examples/tree/master/webpack-example.

The basic approach is to bundle the tests using a webpack entry that loads the testcode and specify that as the suite to load using "suites=..." in the configuration.

One problem I'm running in to is that we sometimes use  require.undef  to unload modules and reload them with stubs. I tried building my own dojo.js that includes require.undef, but somehow that does not seem to get loaded. Also specifying dojo-undef-api:1 in the dojoLoader configuration does not help.
What would be the right way to do this?

**Comment by rhpijnacker** [comment]
Looks like that if I rebuild dojo.js with {dojo-undef-api:1} **and** hack `DojoAMDMainTemplatePlugin.js` to include
`                buf.push("if(loaderScope.require.undef) req.undef = loaderScope.require.undef;");`
then it works.

**Comment by rhpijnacker** [comment]
Although the `.undef()` now works, functionally it does not do what we are using it for (which is: unloading it so it gets reloaded). Is there any change this would work at all in combination with webpack?

**Comment by chuckdumont** [comment]
require.undef won't be of any use because the dojo loader isn't used for loading/defining modules.  Webpack is, and it doesn't support undef.  For our Dojo based applications, we run most of the unit tests against the unpacked modules.

**Comment by chuckdumont** [comment]
@rhpijnacker, please try out require.undef support in release 2.4.2-0 on npm and let me know how it goes.  Thanks.

**Comment by rhpijnacker** [comment]
@chuckdumont I will try to make some time for this, however, I'm a bit swamped at the moment.

**Comment by rhpijnacker** [comment]
The ```.undef()``` seems to work, if I add an extra line to the bootstrap to copy the undef function from the loaderScope.require (like you do with baseUrl, has, etc.) .
Thanks for the good work!

In our tests, we do .undef( ... ) and then trigger a reload by using a nested  define([...], function(dependency) { ... }); to reload the module (or a module that depends on the undeffed module, but with a mock). However, if I use
```
  require([mid], ...)
```
or
```
  define([mid], ...)
```
where ```mid``` is a varable (so not a hardcoded string), then we get the string returned into the callback function, instead of the module reference. Any idea how to fix that?

**Comment by chuckdumont** [comment]
First off, you shouldn't need to copy the undef function from loaderScope.require.  That's the wrong undef. Dojo's undef is not the one that needs to be used because the Dojo loader wasn't used to load the module.  The plugin implements its own undef that undefines the modules for webpack

Did you define the `dojo-undef-api` feature in the loader config `has` property at build time?
```javascript
loaderConfig: {
   has: {
      'dojo-undef-api': true
   }
}
```
The feature must be statically defined at build time in order for the undef api to be enabled.  

Please make sure that you are using the plugin's implementation of undef rather than Dojo's implementation, and if you're still having issues, then please provide a test case that demonstrates the problem.

**Comment by chuckdumont** [comment]
I reproduced the other issue you raised (using variables in array literals for require/define dependencies.  This is unrelated to using undef, so I will open a separate issue for it. 

FYI, a workaround is to define the array as a vaiable:
```javascript
var deps = [mid];
require(deps, ...)
```

**Comment by chuckdumont** [comment]
Opened #130

**Comment by rhpijnacker** [comment]
I did put ```dojo-undef-api``` in the loaderConfig, like suggested.
During debugging, I could see that the conditional code paths for dojo-undef-api are in fact executed, but the ```.undef``` property was ```undefined```.
I'll try to create a test case to show what goes wrong.
(Any suggestions for where to put this?)

**Comment by chuckdumont** [comment]
OK.  Did you pull version 2.4.2-0.  The relevant code change for defining the undef function is [here](https://github.com/OpenNTF/dojo-webpack-plugin/blob/master/lib/DojoAMDMainTemplatePlugin.js#L143)

**Comment by rhpijnacker** [comment]
Yes I did. I see the changes you refer to.

**Comment by chuckdumont** [comment]
WRT the test case, you could create a pull request that adds a failing unit test for your issue.  Use the existing undef unit test as a starting point (located [here](https://github.com/OpenNTF/dojo-webpack-plugin/tree/master/test/TestCases/misc/undefApi)).

**Comment by chuckdumont** [comment]
@rhpijnacker, it turns out there was a bug in the code responsible for querying the `dojo-undef-api` feature from the config.  If the config was specified as a string or function, then the feature was not being properly detected and that could be why it wasn't working for you.  Please try version 2.4.2-3.  This version also has the fix for issue #130.

**Comment by chuckdumont** [comment]
@rhpijnacker, have you had a chance to try 2.4.2-3 yet?

**Comment by chuckdumont** [comment]
Support for `require.undef` and run-time identifiers in dependency arrays is in v2.5.0

**Comment by rhpijnacker** [comment]
@chuckdumont I can confirm that it now works correctly. Thanks for the great support!
