### ISSUE TITLE
dojo-webpack-plugin not working with IE11

### ISSUE THREAD

**Issue by mortelee** [OpenNTF/dojo-webpack-plugin#124]
After running the webpack build we cannot open our application in IE11, because IE11 does not support Object.assign.
Object.assign is used in DojoAMDMainTemplatePlugin.js.

Is it possible to change the code so that it also runs on IE11 or do you have another suggestion to make this work?

**Comment by mortelee** [comment]
We do not use the babel-loader to transform the code es5. So we will first give that a try.

**Comment by chuckdumont** [comment]
Oh, sorry, I wasn't aware of that.  You shouldn't need to use babel.  I'll post a fix soon.

**Comment by chuckdumont** [comment]
Fixed in release 2.4.1
