### ISSUE TITLE
Using this plugin inside ReactJs

### ISSUE THREAD

**Issue by kaczordon** [OpenNTF/dojo-webpack-plugin#154]
I had a question as to whether it would be feasible to try using this loader with React. Specifically I'm looking to be able to incorporate imports of Dojo code into React eg.
`import * as domStyle from 'dojo/dom-style'`

I've looked at the two example projects and they seem to mostly use the normal Dojo syntax for requiring modules. Ideally I would want to be able to bundle the React and Dojo code together. 
```import React from 'react'
import * as domStyle from 'dojo/dom-style'

class App extends Component {
     //react code
     //call dojo module
     componentDidMount() {
          domStyle.set(/*something with the DOM here*/)
     }
}
```
Is there any way to specify which files(specifically the dojo modules) I would want to consume and then send along to be imported with say ES6 import syntax? Is this something this plugin could theoretically support?

**Comment by chuckdumont** [comment]
I've never tried to use import to load Dojo modules, but I can't think of any reason why it wouldn't work.  My suggestion would be to go ahead and try it.  If import doesn't work, CommonJS require should work.

**Comment by kaczordon** [comment]
So using just `require` seems to work in bringing the actual object, but none of the methods can be called and result in errors. Same when  I try to call them as constructors instead to see if that was the issue. With `import` nothing seems to happen and I just get undefined.

I also run into problems when I run the plugin with babel to use ES6/React code.
I get this error:
`Module build failed: Error: Couldn't find preset "es2015" relative to directory "/private/var/folders/ks/b0tr3cj15lx3llcs6rjc3dv40000gn/T/tmp-83656G01beWKNTRU8/dojo"
`

This is what the webpack.config for babel looks like:
```
{
   test: /\.(js|jsx)?$/,
   loader: 'babel-loader',
   exclude: ['/node_modules/', '/dojo/'],
   options: { presets: [ ['es2015', { modules: false }], 'react' ]  }
}
```

What could this be an issue with? Since I'll be using React I'll be transpiling most of the code there anyway.

**Comment by chuckdumont** [comment]
Not sure about your issues, but you can check out the [react-webpack-babel](https://github.com/chuckdumont/react-webpack-babel) fork I created.  It does just what you're looking for (invokes dojo/dom-style from within a react class.

**Comment by GordonSmith** [comment]
Yes it can be done.  This is what I do (there may be better ways):
1.  Create a single webpack package which re-exports the bits of dojo I am interested in ("dojo-shim"):
```
import * as Deferred from "dojo/Deferred";
import * as domConstruct from "dojo/dom-construct";
export {
    Deferred,
    domConstruct
};
```
2.  In my "React" like environment I install "dojo-shim" into package.json and then import as normal:
```
import { Deferred } from "dojo-shim";
```

This works for me as I reuse dojo-shim in several apps.

**Comment by chuckdumont** [comment]
Thanks @GordonSmith.  Closing this issue now.  @kaczordon if you have any more issues/questions, you can reopen.

**Comment by kaczordon** [comment]
Thanks @chuckdumont and @GordonSmith for the help.
