### ISSUE TITLE
Webpack DLLPlugin

### ISSUE THREAD

**Issue by odoe** [OpenNTF/dojo-webpack-plugin#161]
I don't know if this is really an issue, more of a question.

I am trying to utilize the [Webpack DLLPlugin](https://webpack.js.org/plugins/dll-plugin/) to build a manifest of my API. I don't know if it's a workflow thing or something else. The DLLPlugin samples make it look straight forward/

Here is where I create the DLLs using the sample app provided.

```js
// dll.webpack.config.js
const DojoWebpackPlugin = require("dojo-webpack-plugin");
const path = require("path");
const webpack = require("webpack");

module.exports = {
  resolve: {
    extensions: [".js", ".css"]
  },
  entry: {
    commons: ["dojo/_base/lang", "dojo/_base/declare"],
    dijit: ["dijit/layout/TabContainer", "dijit/layout/ContentPane"]
  },
  output: {
    path: path.join(__dirname, "dist"),
    filename: "dojo.[name].js",
    library: "[name]_[hash]"
  },
  plugins: [
    new webpack.DllPlugin({
      path: path.join(__dirname, "dist", "[name]-manifest.json"),
      name: "[name]_[hash]"
    }),
		new DojoWebpackPlugin({
			loaderConfig: require("./js/loaderConfig"),
			environment: {dojoRoot: "dist"},	// used at run time for non-packed resources (e.g. blank.gif)
			buildEnvironment: {dojoRoot: "node_modules"}, // used at build time
			locales: ["en"]
		})
  ],
};
```

My DLLs get generated fine. I can check the output and see my dojo/dijit deps just fine.

Then I try to use them here.

```js
// webpack.config.js
...
	plugins: [
		new webpack.DllReferencePlugin({
			context: path.join(__dirname, "..", "dist"),
			manifest: require("./dist/commons-manifest.json")
		}),
		new webpack.DllReferencePlugin({
			context: path.join(__dirname, "..", "dist"),
			manifest: require("./dist/dijit-manifest.json")
		}),
		new DojoWebpackPlugin({
			loaderConfig: require("./js/loaderConfig"),
			environment: {dojoRoot: "dist"},	// used at run time for non-packed resources (e.g. blank.gif)
			buildEnvironment: {dojoRoot: "node_modules"}, // used at build time
			locales: ["en"]
		})
        ],
...
```

No errors, but the DLLs don't seem to get utilized. I've tried switching the order of DLL refs and dojo-webpack-plugin around and no luck.

I was expecting that Webpack would see the output the dojo-webpack-plugin is passing into the build and utilize the DLLs, but maybe that's not how it works.

I was curious if there was something I was missing related to the dojo-webpack-plugin and how it's used or if anyone has tried this before.

Thanks!

**Comment by odoe** [comment]
I thought I would just update where I ended up with creating DLLs and using the plugin.

I got it to work, sorta.

The key was `context` and `globalContext`.

```js
 new webpack.DllPlugin({
  context: path.join(__dirname, "node_modules", "dojo"),
  path: path.join(__dirname, "dist", "[name]-manifest.json"),
  name: "[name]_[hash]"
}),
new DojoWebpackPlugin({
  globalContext: path.join(__dirname, "node_modules", "dojo"),
  loaderConfig: require("./js/loaderConfig"),
  environment: { dojoRoot: "dist" },
  buildEnvironment: { dojoRoot: "node_modules" },
  locales: ["en"]
});

// Then I can use it
new webpack.DllReferencePlugin({
  context: path.join(__dirname, "node_modules", "dojo"),
  manifest: require("./dist/dojo-manifest.json")
}),
new DojoWebpackPlugin({
  loaderConfig: require("./js/loaderConfig"),
  environment: { dojoRoot: "dist" },
  buildEnvironment: { dojoRoot: "node_modules" },
  locales: ["en"]
})
```

That creates the DLLs fine and I can use them and they do get used. But I get `Module not found: dojo/has` once I do.

It was interesting experiment and I'll keep seeing what I can come up with, but progress is progress. If I can get the DLLPlugin working better with the dojo-webpack-plugin, I'll update. Thanks!

**Comment by chuckdumont** [comment]
Hi @odoe.  If you can provide a test case that reproduces the problem, I can take a look at it.

**Comment by chuckdumont** [comment]
If your using DLLPlugin to try to load different parts of your application asynchronously, then are you aware that you can do that without DLLPlugin simply by using async require.  For example, if you do

```javascript
require(["dijit/layout/TabContainer", "dijit/layout/ContentPane"], function(TabContainer, ContentPane) {
...
});
```
then webpack will create a bundle containing TabContainer, ContentPane plus their dependencies that are not included in the base layer, and load that bundle at runtime when the async require function is called.

See the sample application for an example.  It asynchronously loads the code for the content of each tab using this technique.

**Comment by odoe** [comment]
Thanks @chuckdumont 

Here is a quick sample of where I'm at with the DLL stuff.
https://github.com/odoe/dojo-webpack-plugin-sample-dll

My interest in the DLL plugin wasn't so much for dynamic requiring, we're taking advantage of that a lot.

We have a large API that uses the dojo loader (https://github.com/esri/arcgis-js-api/tree/4master) and were interested in essentially creating a single DLL or multiple that would act as sort of build layers. This could help keep the size of individual applications down while sharing a single source of DLL files. At least that was the idea :wink:

We're planning to release a webpack-plugin for our API that wraps this plugin and handles some default config for the user and some other webpack defaults. It's working awesome in our test builds so far, thanks!

**Comment by chuckdumont** [comment]
I tried building the https://github.com/odoe/dojo-webpack-plugin-sample-dll, but I get the following error:
```
C:\git\dojo-webpack-plugin-sample-dll\node_modules\webpack-cli\bin\webpack.js:242
                                throw err;
                                ^

Error: Cannot find module './dist/dojo-manifest.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
```

Did you forget to include some files?

**Comment by odoe** [comment]
Sorry @chuckdumont, I updated the build script to compile the dll before the build now.

```
  "scripts": {
    "build": "npm run dll && npm run prod",
    "dll": "webpack --config dll.webpack.config.js",
    "prod": "webpack --env.prod"
  }
```

**Comment by chuckdumont** [comment]
Try version 2.7.3-0

**Comment by odoe** [comment]
That''s working with the sample now! Greta work, thanks!
