### ISSUE TITLE
plugin not compatible with old IE

### ISSUE THREAD

**Issue by rbuels** [OpenNTF/dojo-webpack-plugin#162]
What browsers do you aim to support?  v2.7.1 doesn't support IE 10 and below, at least, because of use of `const`:

![image](https://user-images.githubusercontent.com/73749/38400072-141acc8e-3903-11e8-8eff-13cfbb5e513b.png)

https://caniuse.com/#search=const

**Comment by chuckdumont** [comment]
Sorry.  That was an oversight on my part.  The intent is to support IE9 and above.  Will fix.
