### ISSUE TITLE
Modules can't be found when using the commons chunk plugin

### ISSUE THREAD

**Issue by maier49** [OpenNTF/dojo-webpack-plugin#173]
When using the commons chunk plugin, the call to `registerAbsMids` is after the loader actually attempts to resolve the modules in the chunk and fails. This can be seen in [this branch](https://github.com/maier49/dojo-webpack-plugin-sample/tree/chunk-bug) of the sample app. It will build fine, but fails with an error that `dojo/has` cannot be found. 

I've opened [a PR](https://github.com/OpenNTF/dojo-webpack-plugin/pull/172) that emits the call before the code and created [another branch](https://github.com/maier49/dojo-webpack-plugin-sample/tree/chunk-bug-fix) of the sample app that uses a tarball with this fix.

**Comment by chuckdumont** [comment]
Fixed by #172
