### ISSUE TITLE
"SyntaxError: Invalid Unicode escape sequence"

### ISSUE THREAD

**Issue by fkranenburg** [OpenNTF/dojo-webpack-plugin#174]
Could you please take a look at [this issue](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/88)? I'm using  '[extract-css-chunks-webpack-plugin](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin)' with this plugin and it looks like this plugin broke it since version 2.7.1. 

A mentioned in that issue I have a reproducable example: [here](https://github.com/fkranenburg/ExtractCssChunks-issue)

**Comment by chuckdumont** [comment]
Please try v2.7.5-3 on npm.  Thanks
