### ISSUE TITLE
Question about "Use of run-time identifiers and expressions in dependency arrays"

### ISSUE THREAD

**Issue by GordonSmith** [OpenNTF/dojo-webpack-plugin#183]
Is it possible to dynamically load some AMD module at runtime?  

I tried the following (old webpack trick) without success:

```
window["require"]([someRuntimeModule], function(myModule) {})
```

Note:  I do not know what the "someRuntimeModule" might be at build time - I just know it starts with "plugins/"

**Comment by chuckdumont** [comment]
It's not possible to load arbitrary modules at runtime that are not part of the webpack build.

If, however, the plugin modules can be included as part of the build, then you can load them in advance without defining them with the dojo/has loader plugin.   For example:

```javascript
define(['dojo/has!undefined?plugins/a', 'dojo/has!undefined?plugins/b'], function() {});
```
When the above module is loaded, the referenced plugins will be loaded but will remain uninitialized (i.e. their define function callbacks will not be invoked).  You should then be able to `require` them using a runtime expression as in your example.

Currently, a module must be loaded on the client in order for webpack to be able to map the module's Dojo name to a webpack module id at runtime.

**Comment by GordonSmith** [comment]
Thanks for the confirmation - in case anyone else lands here, I resorted to using a different "require" for the runtime loading (in this case d3-require):
```
import { requireFrom as d3RequireFrom } from "d3-require";

const runtimeRequire = d3RequireFrom(async name => {
    return `./${name}.js`;
});

...
runtimeRequire ("plugins/someAMDModule").then(someAMDModule=>{
});
```

Type of thing.
