### ISSUE TITLE
dojoConfig alias path not resolved by webpack

### ISSUE THREAD

**Issue by alexandre-combemorel** [OpenNTF/dojo-webpack-plugin#204]
Hi folk,

Not sure if it's an issue or if I'm doing something wrong, but here is my problem.
I'm having module loaded that way in my app:

```
define([
    "dojo/_base/declare",
    "esri/Map",
    "esri/config",
    "dojo/_base/array",
    "dojo/promise/all",
    "app/Coordinates",
    "app/tasks/Print"
	], function(...)) {}
```
	
Where "app" path is an alias defined in the dojoConfig as follow:

```
packages: [
	{
		name: "app",
		location: base + "/js/map"
	}
]
```

I'm trying to get webpack to solve this path by providing the loaderConfig as mentionned in the doc, with a function and it should take into account my packages variable, or even path that I defined right? 
As mentionned here https://github.com/OpenNTF/dojo-webpack-plugin#the-dojo-loader-config.

Unfortunately I get a error message telling me 

> Module not found: Error: Can't resolve 'app/Coordinates'

for example.

Do you have any idea how webpack handle the dojoConfig pass as an argument in the dojo-webpack-plugin and how to make this alias path resolvable.

Thanks a lot.

**Comment by chuckdumont** [comment]
Not really enough information here to determine the problem.  Can you provide a test case that reproduces the issue?

**Comment by alexandre-combemorel** [comment]
Sorry for the late answer, I will provide it soon, just need to simplify the project to provide a simple use case.

**Comment by chuckdumont** [comment]
@alexandre-combemorel - Have you found a solution to your problem?  Can this issue be closed?

**Comment by alexandre-combemorel** [comment]
Sorry @chuckdumont, I unfortunately don't have the time right now to provide a test example.
You can close the issue and when I find the time, I make sure to open a new one with the necessary example source code.
Thanks for you time.

**Comment by chuckdumont** [comment]
OK, thanks.  Perhaps you can provide more details about your issue, including your webpack.config.js, loaderConfig and your build directory layout.  Also, the complete build output log, including the command line.

**Comment by chuckdumont** [comment]
Closing due to lack of response.
