### ISSUE TITLE
Question about how to handle "define cannot be used indirect" error in loading an application built with webpack

### ISSUE THREAD

**Issue by ChrisHarvey77** [OpenNTF/dojo-webpack-plugin#261]
Hi Chuck,

We have another question to which we haven't been able to find a solid answer.

We have some code that looks like the following:

```javascript
var modulesToLoad = [
    "dojo/_base/declare",
    "dojo/_base/lang",
    "dijit/layout/_LayoutWidget",
    "dijit/_TemplatedMixin",
    "dijit/Destroyable",
    // other local modules
];

if (<condition> ) {
     modulesToLoad = modulesToLoad.concat([<OPTIONAL_MODULE>]);
}

define (modulesToLoad, function( .... ) {
....
)};
```

We are able to build this code using webpack. However, when we load the application, we receive the **_"define cannot be used indirect"_** error.

As a temporary workaround, we are simply adding the optional module to the entire array and passing that to **define**: 

```javascript
define([
    "dojo/_base/declare",
    "dojo/_base/lang",
    "dijit/layout/_LayoutWidget",
    "dijit/_TemplatedMixin",
    "dijit/Destroyable",
    "<OPTIONAL_MODULE>"
], 
```

We think that we're likely just missing some plugin in our webpack.config.js that will allow an array variable to be used in **define**. Can you confirm that? Is there something else we're missing?

Thanks!
-Chris

**Comment by chuckdumont** [comment]
You're not missing anything.  With webpack, dependencies have to be resolvable at build time.  Using a runtime expression (such as a javascript variable) is not supported.

One option to get around this is to use the dojo/has loader plugin.  For example you could do the following:

Before you load the module with the conditional dependency:
```javascript
has.add('loadFoo', condition, true, true);
```

And in your module with the conditional dependency do:
```javascript
define([
    "dojo/_base/declare",
    "dojo/_base/lang",
    "dijit/layout/_LayoutWidget",
    "dijit/_TemplatedMixin",
    "dijit/Destroyable",
    "dojo/has!loadFoo?foo"
], 
```

See [The dojo/has loader extension](https://github.com/OpenNTF/dojo-webpack-plugin#the-dojohas-loader-extension) for more details.

**Comment by ChrisHarvey77** [comment]
Thanks for the detailed response, as always!
