### ISSUE TITLE
Dojo 1.6 compatibility

### ISSUE THREAD

**Issue by pavel-redkin** [OpenNTF/dojo-webpack-plugin#268]
Hi !
Is there any release, that is compatible with Dojo 1.6 ?
Thx

**Comment by chuckdumont** [comment]
I'm not aware of any issues with 1.6,  The sample app builds and runs fine.  What kind of problem are you encountering?

**Comment by pavel-redkin** [comment]
Thanks for your reply
Introduction mentions: "Dojo versions 1.10 and greater."
Dojo 1.10 has backward incompatibility with Dojo 1.6
I clarified in advance, if Dojo 1.6 is OK

I will use dojo-webpack-plugin in project

**Comment by chuckdumont** [comment]
Ugh.  My apologies.  I mis-read your question as asking about Dojo 1.16.  Dojo 1.6 is not even AMD, so no, dojo-webpack-plugin cannot support it and never will.  Sorry for the confusion.
