### ISSUE TITLE
webpack/bootstrap issues interacting with the dojo.js (dojoLoader) 

### ISSUE THREAD

**Issue by tusharosu** [OpenNTF/dojo-webpack-plugin#274]
We have a webpack based application where we create a table using dgrid. When we load the application, the "click and select" functionality is broken on the grid.

On debugging the built application using the source maps, we were able to get to why the issue is occurring but we are not sure what the actual fix should be.

Here is what we see happening:

In webpack/bootstrap, we see the following code (coming from dojo-webpack-plugin):

```javascript
var loaderScope = {document:globalObj.document};
loaderScope.global = loaderScope.window = loaderScope;
globalObj.dojoConfig = globalObj.dojoConfig || {}
var userConfig = mix(globalObj.dojoConfig, ({'baseUrl':'.','packages':[({'name':'mw-navigationbar','location':'./release/derived/ui/mw-navigationbar','lib':'.'}), ... <other packages omitted for readability>],'deps':['bootstrap'],'async':false,'supportedLocales':['ja-jp','en-us','it-it']}));
var defaultConfig = ({'hasCache':({'webpack':1,'host-browser':1,'dom':1,'dojo-loader':1,'dojo-has-api':1,'dojo-dom-ready-api':1,'dojo-sniff':1,'dojo-test-sniff':1,'config-deferredInstrumentation':1,'config-tlmSiblingOfDojo':1})});
var dojoLoader = __webpack_require__(0);
dojoLoader.call(loaderScope, userConfig, defaultConfig, loaderScope, loaderScope); // "this" is an "Object" that has "window" and "global" defined
['baseUrl','has','rawConfig','on','signal'].forEach(function(name) {req[name] = loaderScope.require[name]})
```

In the dojo.js code for the dojoLoader call, we see:
```javascript
...
global = this, // sets "global" to "Object" when we think it expects a "window"
doc = global.document,
element = doc && doc.createElement("DiV"),
has = req.has = function(name){
return isFunction(hasCache[name]) ? (hasCache[name] = hasCache[name](global, doc, element)) : hasCache[name];
},
```

when the ```has = req.has = function(name){``` line above is called from our dgrid/util/has-pointer.js file:

```javascript
define(["dojo/has"], function (has) {
    has.add("pointer", function (global) {
        return "PointerEvent" in global ? "pointer" :
            "MSPointerEvent" in global ? "MSPointer" : false;
    });
    var pointer = has("pointer"), //calls into the dojo.js code
        MSPointer = pointer && pointer.slice(0, 2) === "MS";
    var hasPointer = {};
    hasPointer.pointer = pointer;
    hasPointer.MSPointer = MSPointer;
    return hasPointer;
});
```

, the "this" object comes back as "window" but since dojo.js uses "global" (which is already set to "Object"), the call to ```hasCache[name](global, doc, element))``` does not see the "global" parameter as "window" but as "Object" which was set from the bootstrap code. This causes the grid select to fail.

We also have an index-debug.html page that loads the source code directly and everything works as expected (so we can rule out any code related issues as such)

We can get around the issue by using "this" instead of "global" in ```hasCache[name](global, doc, element)``` (from dojo.js) but it does not seem like the final solution as there seems to be an underlying problem that needs to be resolved here.

Are we missing a configuration here or is there something in the bootstrap code that may need fixing to get past this issue (particularly around how the "this" is being set when the dojoLoader call happens the first time i.e. should be "window" instead of "Object")?

Let us know if you need more information or clarity on the issue here.

**Comment by chuckdumont** [comment]
Try adding the following to your webpack config:

```javascript
node: {
   global: true,
},

**Comment by tusharosu** [comment]
Thanks for the suggestion. I tried adding the "node" option to the webpack config but it did not resolve the issue.

To add more context to the issue, see the attached screenshots which shows the difference in the "this" object value for the **index-debug.html** (using source code - which works as expected) 
![index-debug](https://user-images.githubusercontent.com/11762916/73296442-bcd3e980-41d7-11ea-910b-5e149f5b443f.PNG)

and the **index.html** (using the minified bundle) page
![index](https://user-images.githubusercontent.com/11762916/73296441-bcd3e980-41d7-11ea-9741-2ac8f4624600.PNG)

**Comment by chuckdumont** [comment]
Looking at your dojo.js source, it seems as if you're using a pre-1.10 version of Dojo.  As stated in the README, dojo-webpack-plugin supports Dojo 1.10 and greater.  I suggest you try upgrading to a more recent version of Dojo.

**Comment by chuckdumont** [comment]
Sorry, looks like the change for assigning global in dojo.js went in to a minor release of 1.11.  Please upgrade Dojo to 1.11.8.  That should resolve your problem.

**Comment by tusharosu** [comment]
Thanks! I tried upgrading the dojo version to 1.11.8 but still get the same result (probably because even if the globalObj is set to window or global, it is always an "Object" because of how these are set using the loaderScope? -and based on my limited knowledge of how the dojo-webpack-plugin works, I could be totally off-track here)

Below is the code that I am referring to:
```javascript
buf.push(`var loaderScope = {document:globalObj.document};`);
buf.push(`loaderScope.global = loaderScope.window = loaderScope;`);
```

![dojo-1 11 8](https://user-images.githubusercontent.com/11762916/73302665-fc540300-41e2-11ea-8987-280766df03cf.PNG)

Is there something that needs fixing in the bootstrap code too?

**Comment by chuckdumont** [comment]
OK, I see now.  The scope used to run the loader is kept separate from the global scope so that the loader can add it's global properties ('require', 'define', etc.) without these being in the global scope.

Please try release 2.8.14-rc1.  This should fix the problem as long as no one tries to add new global properties in their has.add callback (would be a pretty hacky thing to do).

**Comment by tusharosu** [comment]
Works like a charm! Thanks!
