### ISSUE TITLE
require.toUrl does not resolve correctly in the webpack bundle

### ISSUE THREAD

**Issue by tusharosu** [OpenNTF/dojo-webpack-plugin#281]
The generated webpack bundle does not seem to resolve the require.toUrl path correctly for the code below :

```javascript
        _createResizeAffordance: function () {
            var resizeAppToggleParams = {
                ....
                image: require.toUrl("clientmdwas-session/images/make_small.svg"),
               ........
            };
            this.resizeToggleButton = new ToggleRowButton(resizeAppToggleParams);
            this.resizeToggleButton.setVisible(false);
        }
```

loaderConfig.js
```javascript
function getConfig(env) {
	dojoConfig = {
		baseUrl: '.',
		packages: [		{
				name: 'clientmdwas-session',
				location: env.dojoRoot + 'session/clientmdwas-session',
				lib: '.'
			}
		],
		deps: ["bootstrap"],
		async: false
	};
	dojoConfig.supportedLocales = ['en-us','it-it'];
	return dojoConfig;
}
```

webpack.config.js
```javascript
        entry: entryPoints,
        output: {
            path: path.resolve(component_path, "release"),
            publicPath: outputPublicPath,
            pathinfo: true,
            filename: "bundle.[name].js"
        },
        module: {
         ....
                    {
                    test: /\.(svg)$/i,
                    issuer: {
                    	include: /\.(css|scss)$/
                    },
                    use: [{
                        loader: 'file-loader',
                        options: {
                            limit: 100000,
                            outputPath: 'images'
                        }
                        
                    }]
                },
                {
                    test: /\.(svg)$/i,
                    issuer: {
                    	include: /\.(js|html)$/
                    },
                    use: [{
                        loader: 'svg-inline-loader',
                        options: {
                            limit: 100000,
                            outputPath: 'images'
                        }
                        
                    }]
                }
         ....
        },
        plugins: [
            new DojoWebpackPlugin({
                loaderConfig: require(path.resolve(sbroot,  "/loaderConfig")),
                environment: {dojoRoot: "./release"},   
                buildEnvironment: {dojoRoot: sbroot}, 
                async: true
            }),
```
Relevant portion of the output bundle.js file (e.toUrl does not get resolved as expected):
```javascript

_createResizeAffordance:function(){var n={state:!1,image:e.toUrl("clientmdwas-

session/images/make_small.svg"), ........

```
The svg image also does not get copied to the release/images folder.

Are we missing some configuration here or is there some way to work around this issue?

**Comment by chuckdumont** [comment]
What is the value returned by toUrl?  I notice that the input to toUrl is a relative path.  Make sure that you're using a context require instead of the global require in your module.

WRT copying images to the release/images folder.  dojo-webpack-plugin doesn't do this.  You need to do it as part of your build process.  You can use the CopyWebpackPlugin.  See the sample application for an example.

**Comment by chuckdumont** [comment]
Actually, I don't think that using context require will give you what you want either.  But I still think your problem is related the package location for `clientmdwas-session` using a relative path.  Try using 
```javascript
environment: {dojoRoot: "release"},
```
instead of 
```javascript
environment: {dojoRoot: "./release"},
```

**Comment by tusharosu** [comment]
Hi Chuck,

Thanks for the suggestions. I will try these out and provide you with the required information soon.
Stay safe!

Thanks,
Tushar

**Comment by chuckdumont** [comment]
@tusharosu - Did you resolve your problem?  Can this issue be closed?

**Comment by tusharosu** [comment]
Thanks for the suggestions and all your help. The issue was related to the image files not getting copied to the release folder. require.toUrl works fine when the copy is done explicitly. We need to figure out how to smartly handle this copying of resources. Closing the issue now.

**Comment by phil0135** [comment]
One hint if someone else has a similar problem:
require.toUrl does only work in packed version if in the loader config the **location** attribute in dojoConfig.packages can be correctly resolved during runtime.
In my case I used a custom variable to set **location** attribute in dojoConfig.packages, but I only set the variable in DojoWebpackPlugin.buildEnvironment and not in DojoWebpackPlugin.environment
