### ISSUE TITLE
Dojo layer file doesn't show the content 

### ISSUE THREAD

**Issue by muruswam** [OpenNTF/dojo-webpack-plugin#327]
When I try to load dojo layer file, and verify it in the source tab of the dev console in chrom browser, it displays as //>>built
//# sourceMappingURL=assuranceDashboard.js.map as the content, not able to see the actual layer minified content. any idea why ? I see that in the later point of time, whenever I refer a widget which declared inside layer file, getting downloaded as a seperate request from server, not loading/referring from layer file. 

Any issue with layer file ? of browser.

**Comment by chuckdumont** [comment]
Not sure I understand your issue.  Perhaps some screen-shots would help.

**Comment by chuckdumont** [comment]
Closing due to lack of response.  Feel free to update this issue if you are still having problems.
