### ISSUE TITLE
Splitting applications into multiple bundles

### ISSUE THREAD

**Issue by phoragroup** [OpenNTF/dojo-webpack-plugin#328]
I new to webpack and the dojo-webpack-plugin.  I have a very large dojo 1.16 application that is broken up into a series of modules and are loaded when needed.  I have been able to webpack the application as one large package.  However, I would like to exclude dojo and dijit from being included in the package and be able to bundle the different parts of the application into individual packages.  Do I need to create layers the dojo profile or can I do it within webpack? Since I am new to this, can you provide any instructions or explanations.  thanks.

**Comment by chuckdumont** [comment]
The webpack name for layer is bundle.  See the [SplitChunksPlugin](https://webpack.js.org/plugins/split-chunks-plugin/) for details.  Note that if what you're after is progressive loading of the application, this requires active participation on the part of the application.  You're application needs to use the async require function to asynchronously load parts of your application based on how the user navigates your app.  See the dojo-webpack-plugin sample for an example of how to do this.  Each tab displays a different dojo widget, the code for which is loaded when the user opens the tab.  Without use of async require to load parts of your app, SplitChunksPlugin can split your app into smaller bundles, but all the bundles will need to be loaded before your app can run.  You may see some benefit from improved cacheability of smaller bundles and parallel loading, but no where near as much as if your app were designed to progressively load parts of the application on demand.

When you use async require, webpack will normally create separate bundles on it's own.

**Comment by phoragroup** [comment]
Thank you, do I break out dojo/dijit  the same way using the SplitChunksPlugin?

**Comment by chuckdumont** [comment]
You could do that if you wanted to.

**Comment by phoragroup** [comment]
Thanks, I will try it out today.
