### ISSUE TITLE
webpack-hasjs-plugin does not appear to work with 3.0.0-rc1

### ISSUE THREAD

**Issue by GordonSmith** [OpenNTF/dojo-webpack-plugin#333]
webpack-hasjs-plugin is causing build issue with webpack v5

**Comment by chuckdumont** [comment]
I haven't gotten to that plugin yet.  Just disable it for now.  Your app should build fine without it.

**Comment by GordonSmith** [comment]
Yea - I suspected as much (and had already done that) - one weirdness is I am seeing this in my dist folder:
![image](https://user-images.githubusercontent.com/966863/121956095-9d9c1480-cd58-11eb-9f39-4f9f3870fa54.png)

Where the 421.js appears to be getting pulled in by:
```
	if(has("dojo-sync-loader") && dojo.config.parseOnLoad && !dojo.isAsync){
		ready(99, function(){
			if(!dojo.parser){
				dojo.deprecated("Add explicit require(['dojo/parser']);", "", "2.0");
				__webpack_require__.e(/*! AMD require */ 421).then(function() {[__webpack_require__(/*! dojo/parser */ 2421)];}).catch(__webpack_require__.oe);
			}
		});
	}
```

Not sure if that is of interest?

**Comment by chuckdumont** [comment]
No idea.  You might try setting 
```javascript
optimization: {
   chunkIds: 'named'
}
```
to get more meaningful bundle names.

**Comment by chuckdumont** [comment]
webpack-hasjs-plugin version 1.0.4 now supports webpack 5.
