### ISSUE TITLE
dojo.js:56 [HMR] Update check failed: Error: __webpack_require__.dj name collision.

### ISSUE THREAD

**Issue by ferrykranenburgcw** [OpenNTF/dojo-webpack-plugin#339]
When I update a non-dojo file (in this case a Vue file) and have a running dev server with HMR active I receive this error in my browser. Because of this the page is not updated (I think). Is there a way to prevent this from happening?

`dojo.js:56 [HMR] Update check failed: Error: __webpack_require__.dj name collision.`

![image](https://user-images.githubusercontent.com/83816575/122196887-edcdc080-ce97-11eb-8e3f-9755f93a0012.png)

**Comment by chuckdumont** [comment]
Edit the file node_modules/dojo-webpack-plugin/lib/DojoAMDRuntimeModule.js and remove line:
```javascript
		buf.push(`if (${djProp}) throw new Error("${djProp} name collision.")`);
```
and see if that resolves the issue.

**Comment by ferrykranenburgcw** [comment]
Yes, this works. Non-dojo updates are reloaded automatically again.

**Comment by ferrykranenburgcw** [comment]
Nice and so fast! When is the next release planned?
