### ISSUE TITLE
Location is undefined

### ISSUE THREAD

**Issue by BKrewer** [OpenNTF/dojo-webpack-plugin#346]
Hi, 

I'm trying to add the plugin along with the webpack, but when running the following error is displayed:

![image](https://user-images.githubusercontent.com/39016677/133679458-688a247e-4d8c-4e18-8830-f67ac4eb0773.png)

After click on error: 
![image](https://user-images.githubusercontent.com/39016677/133679524-6453c31b-3b02-4edc-8fae-30d54d143a20.png)

Webpack: 
![image](https://user-images.githubusercontent.com/39016677/133679584-85401550-6d7d-4abb-949a-071b4c03a0cd.png)

loaderconfig default of example (https://github.com/OpenNTF/dojo-webpack-plugin-sample/blob/master/js/loaderConfig.js)

Webpack v5 and node v14 and dojo 1.16.4

**Comment by chuckdumont** [comment]
Are you seeing this error when building or when try to running the built code?  What target environment are you running in.  Note that dojo-webpack-plugin does not support node.js as a target platform.  Only browser platforms are supported.

**Comment by BKrewer** [comment]
I get error in compilation when running `npx webpack --config webpack.config.js`. I changed the target to "web" in webpack.config file and the same error follows.
Would there be any other example configuration besides the loaderConfig file?

**Comment by chuckdumont** [comment]
I don't think it's the config file.  Could you post a test case that reproduces the problem?

**Comment by henry-filosa** [comment]
Hi, I'm also having the same exact issue. In our case, this is in conjunction with the [Cypress/webpack-preprocessor](https://www.npmjs.com/package/@cypress/webpack-preprocessor). 
```
ReferenceError: location is not defined
    at /home/henryfilosa/everlaw/servers/assets/target/generated-webapp/libs/dojo-release-1.16.4/dojo/dojo.js:8:2740
    at Object.<anonymous> (/home/henryfilosa/everlaw/servers/assets/target/generated-webapp/libs/dojo-release-1.16.4/dojo/dojo.js:8:22014)
    at DojoLoaderPlugin.createLoaderScope (/home/henryfilosa/everlaw/servers/assets/node_modules/dojo-webpack-plugin/lib/DojoLoaderPlugin.js:167:94)
    at Hook.eval (eval at create (/home/henryfilosa/everlaw/servers/assets/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at Hook.CALL_DELEGATE [as _call] (/home/henryfilosa/everlaw/servers/assets/node_modules/tapable/lib/Hook.js:14:14)
    at /home/henryfilosa/everlaw/servers/assets/node_modules/dojo-webpack-plugin/lib/DojoLoaderPlugin.js:206:68
    at /home/henryfilosa/.cache/Cypress/8.3.1/Cypress/resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```
Please let me know of any information that could be useful for figuring this out.

**Comment by henry-filosa** [comment]
I noticed this line on the readme: "The Dojo loader builder requires that the Dojo util directory is a sibling of the dojo directory and is named either util or dojo-util." We do not have a util directory in our dojo package. However, would we get to this point in the process if that was the issue?

**Comment by chuckdumont** [comment]
> We do not have a util directory in our dojo package

dojo-util is not *in* the dojo package.  It is a peer dependency.  So dojo-util should be in node_modules, along-side dojo.

**Comment by chuckdumont** [comment]
Just to clarify.  Building your own dojo loader is not an alternative to building against the dojo sources.  Whether or not you allow dojo-webpack-plugin to build the loader or you use a pre-built loader, you still need to run webpack against the dojo source code and not a release build.

**Comment by henry-filosa** [comment]
Thanks for responding. That clears things up, we weren't managing our dojo packages with npm. Downloaded the necessary libraries and instead are having issues with [`publicPath`](https://webpack.js.org/guides/public-path/), but that's a battle for another day.
