### ISSUE TITLE
Better dojo/text! loader replacement for JSON files

### ISSUE THREAD

**Issue by anitschke** [OpenNTF/dojo-webpack-plugin#375]
There is some discussion in https://github.com/OpenNTF/dojo-webpack-plugin#dojo-loader-extensions about how the dojo-webpack-plugin does some replacements of the `dojo/text!` loader for you automatically. I have found that this isn't sufficient for JSON files since webpack handles those on it's own.

using `dojo/text!` for JSON files in my code results in the following error:
```
ERROR in package/myfile.json (./node_modules/dojo-webpack-plugin/loaders/dojo/text/index.js!package/myfile.json)
Module parse failed: Unexpected token "m" (0x6D) in JSON at position 0 while parsing near "module.exports = \"{\\..."
File was processed with these loaders:
 * ./node_modules/dojo-webpack-plugin/loaders/dojo/text/index.js
You may need an additional loader to handle the result of these loaders.
JSONParseError: Unexpected token "m" (0x6D) in JSON at position 0 while parsing near "module.exports = \"{\\..."
    at JsonParser.parse (/project/ui/src/main/js/node_modules/webpack/lib/json/JsonParser.js:43:7)
    at /project/ui/src/main/js/node_modules/webpack/lib/NormalModule.js:1087:26
    at processResult (/project/ui/src/main/js/node_modules/webpack/lib/NormalModule.js:800:11)
```

I have found that I can fix this issue by using NormalModuleReplacementPlugin to entirely remove the loader for json files so that webpack can just load the json on it's own without issues.

```js
new webpack.NormalModuleReplacementPlugin(/^dojo\/text!/, function(data) {
        data.request = data.request.replace(/^dojo\/text!(.*\.json)$/, '$1');
    }),
```

It would be nice if dojo-webpack-plugin provided this along with the other default `dojo/text!` replacement

**Comment by chuckdumont** [comment]
@anitschke - is your source code explicitly specifying dojo/text when loading myfile.json (e.g. 'dojo/text!myfile.json')?  If so, then I would expect the behavior you describe and your solution seems like the right one.

**Comment by anitschke** [comment]
Yes, it is doing `dojo/text!myfile.json`. That being said I jumped the gun on creating this issue a little. The above replace gets the build to work but when I try to test it out I am noticing that I am still having some issues. Webpack is loading it as an JS object and not a string, resulting in `JSON.parse` erroring out. Still trying to figure out this piece of the puzzle.

**Comment by chuckdumont** [comment]
By default, webpack uses json-loader to load json files.  Sounds like you need them loaded as test.  Just define a loader to do this in your weback-config.

```javascript
module.exports = {
  module: {
    loaders: [
      {
        test: /\.json$/,
        loader: 'raw-loader'
      }
    ]
  }
}
```

**Comment by chuckdumont** [comment]
Thanks @anitschke.  I don't understand the esModule option either, but hopefully others will find this post helpful.
