### ISSUE TITLE
Erros while processing dojo plugins

### ISSUE THREAD

**Issue by rhpijnacker** [OpenNTF/dojo-webpack-plugin#43]
I'm trying to bundle our dojo application using dojo-webpack-plugin. While compiling I get errors for places where we use dojo plugins:

```
Module not found: Error: Can't resolve 'dojo/domReady' in ...
Module not found: Error: Can't resolve 'raw-loader' in ...
```
 (where the raw-loader is actually dojo/text! in the original source code).

Also for some custom plugins that we created, the same error occurs. How should we deal with this?

**Comment by chuckdumont** [comment]
For the raw-loader problem, make sure you have the following in your webpack.config.js:
```javascript
	resolveLoader: {
		modules: [
			path.join(__dirname, "node_modules")
		]
	}
```

For the rest of the plugins, see the [Dojo Loader Extensions](https://github.com/OpenNTF/dojo-webpack-plugin#dojo-loader-extensions) section of the README.  For dojo/domReady, you should replace this with calling dojo/ready from within your code.  Dojo loader plugins that complete asynchronously are incompatible with webpack's synchronous loader architecture.  The [dojo/loaderProxy](https://github.com/OpenNTF/dojo-webpack-plugin#the-dojoloaderproxy-loader-extension) webpack plugin (included with dojo-webpack-plugin) allows some Dojo loader plugins to work with webpack provided that the plugin's `load()` method can be made to complete synchronously.  See the README for details.

**Comment by rhpijnacker** [comment]
Hi Chuck, 

Thanks for the response!
The part with the "resolveLoader" is already there, and the raw-loader is in node_modules. Does the order matter (I would hope not...)

Ronald
