### ISSUE TITLE
nls + dojo calendar issue

### ISSUE THREAD

**Issue by GordonSmith** [OpenNTF/dojo-webpack-plugin#69]
Irrespective of what locales the user has specified in their DojoWebpackPlugin options, **all** locales must be included for the dojo calendar (dojo/cldr/nls).

I am guessing this is because the various calendars (dojo/cldr/nls/gregorian.js) reference them all specifically.

Steps to reproduce:
* Build sample application with a subset of the locales it references (e.g. "en").
* Open the sample app in a browser configured with "en-gb"

Note:
* It won't fail if opened in a locale that it does not "know" about e.g. "en-ie".

**Comment by chuckdumont** [comment]
OK, thanks.  I think what needs to happen is that the i18n loader needs add dependencies for all available locales that match, with greater specificity, the locales specified in the `locales` option.   Looking into this.

**Comment by GordonSmith** [comment]
FWIW This is not just limited to calendar I can also reproduce with a bunch of other dijits...

Also worth noting is that:  https://github.com/OpenNTF/dojo-webpack-plugin/pull/68 did happen to "fix" this issue, as the nls loader gracefully handles the "missing/undefined" modules by design.  (I was a bit surprised that the observed dojo require behaviour was to not fire the callback...).

**Comment by chuckdumont** [comment]
Before I post a release, please get version 2.1.4-rc1 and verify that it resolves your issue.  Thanks.

**Comment by GordonSmith** [comment]
I will re-test (I had posted some comment on the PR:  https://github.com/OpenNTF/dojo-webpack-plugin/pull/72)

**Comment by chuckdumont** [comment]
OK, I think #74 should fix it.  Please try 2.1.4-rc2.

**Comment by GordonSmith** [comment]
2.1.4-rc2 is working well for all the test scenarios I could think of!  thanks.

**Comment by chuckdumont** [comment]
Great! v2.1.4 has been published.  Thanks for all your help.

**Comment by GordonSmith** [comment]
No, thank you for your help!
