### ISSUE TITLE
Incorrect output when using ProvidePlugin together with DojoWebpackPlugin

### ISSUE THREAD

**Issue by rhpijnacker** [OpenNTF/dojo-webpack-plugin#98]
I downloaded the dojo-webpack-plugin-sample and added one line in LazyContentPane.js that uses jquery: 
    `var body = $('body');`
I added the ProvidePlugin to map $ to jquery in webpack.config.js:
    `new webpack.ProvidePlugin({ $: 'jquery' })`
and added jquery to the project:
    `npm install --save-dev jquery@2.1.4`

Now, when I build the project the generated output contains incorrect output at the place where ProvidePlugin tries to insert the $ variable to resolve to jquery (output simplified by removing lots of duplicate lines):

`/* WEBPACK VAR INJECTION */(function($) {
var __WEBPACK_AMD_DEFINE_ARRAY__, __WEBPACK_AMD_DEFINE_RESULT__;
!(__WEBPACK_AMD_DEFINE_ARRAY__ = !(module.exports = , __WEBPACK_AMD_DEFINE_RESULT__ = i.apply(null, __WEBPACK_AMD_DEFINE_ARRAY__),
`

I tried to reproduce this without DojoWebPackPlugin, but then it works correctly.

**Comment by chuckdumont** [comment]
You need to use the [cjsRequirePatterns](https://github.com/OpenNTF/dojo-webpack-plugin#cjsrequirepatterns)  option to ensure that webpack will treat the require call injected by the ProvidePlugin as a CommonJS require instead of Dojo synchronous require.

**Comment by rhpijnacker** [comment]
@chuckdumont Thanks for your response. Unfortunately I do not seem to get this configuration just right.
Actually, adding the line you mentioned does not seem to have much effect. I still get the same output as before.

Kind regards, Ronald

**Comment by chuckdumont** [comment]
Yeah, you found a bug.  Should be fixed in version 2.2.2-rc12 on npm.  Please try it out and let me know.   You still need the cjsRequirePatterns option mentioned above.

**Comment by chuckdumont** [comment]
Closing as fixed in release 2.3.0.  Please re-open if you still have problems

**Comment by rhpijnacker** [comment]
@chuckdumont Thanks for looking in to this.
I can verify that the problem is indeed solved.
